### ISSUE TITLE
[Bug]: Checkbox not rendering

### ISSUE THREAD

**Issue by saade** [GuavaCZ/filament-clusters#4]
### What happened?

The checkbox is not being rendered when inside a cluster.

![image](https://github.com/GuavaCZ/filament-clusters/assets/14329460/33e3d9bd-62e9-4fff-bc87-2c68236d7f8b)

### How to reproduce the bug

```php
Cluster::make()
  ->label(__('Icon color'))
  ->schema([
      Forms\Components\ColorPicker::make('icon_color'),
      Forms\Components\Checkbox::make('icon_no_color'),
  ])->columns(2),
```

### Package Version

LTS

### PHP Version

8.2.x

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
Hi @saade. Thanks for the report.

This is because by default, checkboxes are rendered inline in filament (inside the label), but the plugin removes all labels, hints, and helper texts to be able to render the items in a cluster.

If you want the checkbox to appear, you need to add `->inline(false)`:

```php
Forms\Components\Checkbox::make('icon_no_color')->inline(false),
```

However keep in mind that checkboxes and toggles do not look too good inside a cluster.
